sambal/urls.py
from django.conf.urls import patterns,url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^login/$','django.contrib.auth.views.login',{'template_name':'login.html'},name='sambal_login'),
    url(r'^logout/$','django.contrib.auth.views.logout',{'template_name':'logout.html'},name='sambal_logout'),
    url(r'^(?P<user_id>\d+)/edit/$','sambal.views.edit',name='sambal_edit'),
    url(r'^new/$','sambal.views.create',name='sambal_new'),
    url(r'^success/$',TemplateView.as_view(template_name='user_success.html'),name='sambal_success'),
    url(r'^(?P<user_id>\d+)/profile/$','sambal.views.user_profile',name='sambal_profile'),
)

sambal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

CHOICE_STATE = (
    ('KUL','Kuala Lumpur'),
    ('LBN','Labuan'),
    ('PJY','Putrajaya'),
    ('JHR','Johor'),
    ('KDH','Kedah'),
    ('KTN','Kelantan'),
    ('MLK','Melaka'),
    ('NSN','N. Sembilan'),
    ('PHG','Pahang'),
    ('PRK','Perak'),
    ('PLS','Perlis'),
    ('PNG','P. Pinang'),
    ('SBH','Sabah'),
    ('SRW','Serawak'),
    ('SGR','Selangor'),
    ('TRG','Terengganu'),
)


class UserProfile(models.Model):

    user = models.OneToOneField(User)
    street1 = models.CharField(max_length=30,blank=True)
    street2 = models.CharField(max_length=30,blank=True)
    postcode = models.IntegerField(max_length=5,blank=True,null=True)
    town = models.CharField(max_length=20,blank=True)
    state = models.CharField(max_length=3,choices=CHOICE_STATE)

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    post_save.connect(create_user_profile, sender=User)

sambal/forms.py
from django import forms
from django.contrib.auth.models import User

from sambal.models import CHOICE_STATE


class CreateUserForm(forms.Form):

    username = forms.CharField(
        max_length=30,
        help_text=u"Alphanumeric characters only (letters, digits and underscores). Maximum length is 30.",
        widget=forms.TextInput()
    )
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput,label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput,label='Re-enter password')

    def clean_username(self):
        data = self.cleaned_data["username"]
        if User.objects.filter(username=data).exists():
            raise forms.ValidationError(u"Username already taken.")
        return data

    def clean_email(self):
        data = self.cleaned_data["email"]
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError(u"Email already used.")
        return data

    def clean(self):
        cleaned_data = super(CreateUserForm,self).clean()
        if "password1" in cleaned_data:
            password1 = cleaned_data["password1"]
            password2 = cleaned_data["password2"]

            if password1 != password2:
                msg = u"Your password does not match."
                self._errors["password1"] = self.error_class([msg])
                self._errors["password2"] = self.error_class([msg])
                del cleaned_data["password1"]
                del cleaned_data["password2"]
        return cleaned_data

class UserInformationForm(forms.Form):

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()
    street1 = forms.CharField(max_length=30,required=False)
    street2 = forms.CharField(max_length=30,required=False)
    postcode = forms.IntegerField(required=False)
    town = forms.CharField(max_length=20,required=False)
    state = forms.CharField(widget=forms.Select(choices=CHOICE_STATE))

    def clean_postcode(self):
        data = self.cleaned_data["postcode"]
        if len(str(data)) != 5:
            raise forms.ValidationError(u'Postcode must be 5 number')
        return data

    def clean_email(self):
        data = self.cleaned_data["email"]
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError(u"Email already used.")
        return data

sambal/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_list_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from sambal.forms import CreateUserForm,UserInformationForm
from cencalok.models import Recipe

def create(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(
                form.cleaned_data["username"],
                form.cleaned_data["email"],
                form.cleaned_data["password1"])
            new_user.first_name = form.cleaned_data["first_name"]
            new_user.last_name = form.cleaned_data["last_name"]
            new_user.save()
            return HttpResponseRedirect('/user/success/')
    else:
        form = CreateUserForm()
    return render(request,'create_user.html',{'form':form,})

@login_required()
def edit(request, user_id):
    if request.method == 'POST':
        form = UserInformationForm(request.POST)
        if form.is_valid():
            logged_user = request.user
            logged_user.first_name = form.cleaned_data["first_name"]
            logged_user.last_name = form.cleaned_data["last_name"]
            logged_user.email = form.cleaned_data["email"]
            logged_user_profile = request.user.get_profile()
            logged_user_profile.street1 = form.cleaned_data["street1"]
            logged_user_profile.street2 = form.cleaned_data["street2"]
            logged_user_profile.postcode = form.cleaned_data["postcode"]
            logged_user_profile.town = form.cleaned_data["town"]
            logged_user_profile.state = form.cleaned_data["state"]
            logged_user.save()
            logged_user_profile.save()
            return HttpResponseRedirect('/user/' + str(logged_user) +'/profile/')
    else:
        form = UserInformationForm()
    return render(request,'edit_user.html',{'form':form,})

@login_required
def user_profile(request, user_id):
    recipes = get_list_or_404(Recipe, user_id=user_id)
    return render(request,'user_profile.html',{'recipes': recipes})

sambal/templates/create_user.html
{% extends "sidebar.html" %}

{% block title %}
    Create new user
{% endblock %}

{% block base %}
    {% load url from future %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    <p>Click <a href="/">here</a> to return to home page</p>
    <p>Click <a href="{% url 'sambal_login' %}">here</a> to login.</p>
{% endblock %}

sambal/templates/edit_user.html
{% extends "sidebar.html" %}

{% block title %}
Edit user information
{% endblock %}

{% block base %}
    {% load url from future %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <p>Click <a href="{% url 'sambal_profile' user.id %}">here</a> to return to user profile</p>
{% endblock %}

sambal/templates/login.html
{% extends "sidebar.html" %}

{% block title %}
Login
{% endblock %}

{% block base %}
    {% load url from future %}
    {% if user.is_authenticated %}
        <p>You have logged in. Click <a href="/">here</a> to return to homepage</p>
        <p>Click <a href="{% url 'sambal_logout' %}">here</a> to logout</p>
    {% else %}
        <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
            <input type="hidden" name="next" value="{{ next }}">
        </form>
        <p>Click <a href="/">here</a> to return to home page</p>
        <p>Click <a href="{% url 'sambal_new' %}">here</a> to create new account.</p>
    {% endif %}
{% endblock %}

sambal/templates/logout.html
{% extends "sidebar.html" %}

{% block title %}
Logout
{% endblock %}

{% block base %}
    {% load url from future %}
    You have successfully logout. Click <a href="{% url 'sambal_login' %}">here</a> to login.
{% endblock %}

sambal/templates/user_profile.html
{% extends "sidebar.html" %}

{% block title %}
User information
{% endblock %}

{% block base %}
    {% load url from future%}
    This is your information. <br>
    First name: {{ user.first_name }} <br>
    Last name: {{ user.last_name }}  <br>
    E-mail: {{ user.email }} <br>
    Address:
    {{ user.get_profile.street1 }} <br>
    {{ user.get_profile.street2 }} <br>
    {{ user.get_profile.postcode }} {{ user.get_profile.town }} <br>
    {{ user.get_profile.get_state_display }} <br>
    Click <a href="{% url 'sambal_edit' user.id %}">here</a> to change your information

    <h2>My collections</h2>
    {% for recipe in recipes %}
        <img src="holder.js/128x128">
        <h3><a href="{% url 'cencalok_detail' recipe.id %}">Name: {{ recipe.name }}</a></h3>
        <p>recipe.description</p>
        {% if user.id == recipe.user_id %}
            <p><a href="{% url 'cencalok_delete' recipe.id %}"><button type="submit">Delete</button></a></p>
        {% endif %}
    {% endfor %}

{% endblock %}

sambal/templates/user_success.html
{% extends "sidebar.html" %}

{% block title %}
Success!
{% endblock %}

{% block base %}
    {% load url from future %}
    You has successfully created new user. Please <a href="{% url 'sambal_login' %}">login</a> with your new account.
{% endblock %}